/**
  ******************************************************************************
  * @file    st25dv_reg_wrapper.h
  * @author  MMY Application Team
  * @brief   This file wraps API from ST25DV to ST25DVxxKC
  ******************************************************************************
  * @attention
  *
  * COPYRIGHT 2022 STMicroelectronics, all rights reserved
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
  * AND SPECIFICALLY DISCLAIMING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
  * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef _ST25DV_REG_WRAPPER_H_
#define _ST25DV_REG_WRAPPER_H_

#include "st25dvxxkc_reg.h"

#define ST25DV_WriteReg_Func                                    ST25DVxxKC_WriteReg_Func
#define ST25DV_UID_REG                                          ST25DVXXKC_UID_REG
#define ST25DV_ReadReg_Func                                     ST25DVxxKC_ReadReg_Func
#define ST25DV_RF_MNGT_RFSLEEP_SHIFT                            ST25DVXXKC_RF_MNGT_RFSLEEP_SHIFT
#define ST25DV_RF_MNGT_RFSLEEP_MASK                             ST25DVXXKC_RF_MNGT_RFSLEEP_MASK
#define ST25DV_RF_MNGT_RFSLEEP_FIELD                            ST25DVXXKC_RF_MNGT_RFSLEEP_FIELD
#define ST25DV_RF_MNGT_RFDIS_SHIFT                              ST25DVXXKC_RF_MNGT_RFDIS_SHIFT
#define ST25DV_RF_MNGT_RFDIS_MASK                               ST25DVXXKC_RF_MNGT_RFDIS_MASK
#define ST25DV_RF_MNGT_RFDIS_FIELD                              ST25DVXXKC_RF_MNGT_RFDIS_FIELD
#define ST25DV_RF_MNGT_REG                                      ST25DVXXKC_RF_MNGT_REG
#define ST25DV_RF_MNGT_DYN_RFSLEEP_SHIFT                        ST25DVXXKC_RF_MNGT_DYN_RFSLEEP_SHIFT
#define ST25DV_RF_MNGT_DYN_RFSLEEP_MASK                         ST25DVXXKC_RF_MNGT_DYN_RFSLEEP_MASK
#define ST25DV_RF_MNGT_DYN_RFSLEEP_FIELD                        ST25DVXXKC_RF_MNGT_DYN_RFSLEEP_FIELD
#define ST25DV_RF_MNGT_DYN_RFDIS_SHIFT                          ST25DVXXKC_RF_MNGT_DYN_RFDIS_SHIFT
#define ST25DV_RF_MNGT_DYN_RFDIS_MASK                           ST25DVXXKC_RF_MNGT_DYN_RFDIS_MASK
#define ST25DV_RF_MNGT_DYN_RFDIS_FIELD                          ST25DVXXKC_RF_MNGT_DYN_RFDIS_FIELD
#define ST25DV_RF_MNGT_DYN_REG                                  ST25DVXXKC_RF_MNGT_DYN_REG
#define ST25DV_RF_MNGT_DYN_ALL_SHIFT                            ST25DVXXKC_RF_MNGT_DYN_ALL_SHIFT
#define ST25DV_RF_MNGT_DYN_ALL_MASK                             ST25DVXXKC_RF_MNGT_DYN_ALL_MASK
#define ST25DV_RF_MNGT_ALL_SHIFT                                ST25DVXXKC_RF_MNGT_ALL_SHIFT
#define ST25DV_RF_MNGT_ALL_MASK                                 ST25DVXXKC_RF_MNGT_ALL_MASK
#define ST25DV_RFA4SS_RWPROT_SHIFT                              ST25DVXXKC_RFA4SS_RWPROT_SHIFT
#define ST25DV_RFA4SS_RWPROT_MASK                               ST25DVXXKC_RFA4SS_RWPROT_MASK
#define ST25DV_RFA4SS_RWPROT_FIELD                              ST25DVXXKC_RFA4SS_RWPROT_FIELD
#define ST25DV_RFA4SS_REG                                       ST25DVXXKC_RFA4SS_REG
#define ST25DV_RFA4SS_PWDCTRL_SHIFT                             ST25DVXXKC_RFA4SS_PWDCTRL_SHIFT
#define ST25DV_RFA4SS_PWDCTRL_MASK                              ST25DVXXKC_RFA4SS_PWDCTRL_MASK
#define ST25DV_RFA4SS_PWDCTRL_FIELD                             ST25DVXXKC_RFA4SS_PWDCTRL_FIELD
#define ST25DV_RFA4SS_ALL_SHIFT                                 ST25DVXXKC_RFA4SS_ALL_SHIFT
#define ST25DV_RFA4SS_ALL_MASK                                  ST25DVXXKC_RFA4SS_ALL_MASK
#define ST25DV_RFA3SS_RWPROT_SHIFT                              ST25DVXXKC_RFA3SS_RWPROT_SHIFT
#define ST25DV_RFA3SS_RWPROT_MASK                               ST25DVXXKC_RFA3SS_RWPROT_MASK
#define ST25DV_RFA3SS_RWPROT_FIELD                              ST25DVXXKC_RFA3SS_RWPROT_FIELD
#define ST25DV_RFA3SS_REG                                       ST25DVXXKC_RFA3SS_REG
#define ST25DV_RFA3SS_PWDCTRL_SHIFT                             ST25DVXXKC_RFA3SS_PWDCTRL_SHIFT
#define ST25DV_RFA3SS_PWDCTRL_MASK                              ST25DVXXKC_RFA3SS_PWDCTRL_MASK
#define ST25DV_RFA3SS_PWDCTRL_FIELD                             ST25DVXXKC_RFA3SS_PWDCTRL_FIELD
#define ST25DV_RFA3SS_ALL_SHIFT                                 ST25DVXXKC_RFA3SS_ALL_SHIFT
#define ST25DV_RFA3SS_ALL_MASK                                  ST25DVXXKC_RFA3SS_ALL_MASK
#define ST25DV_RFA2SS_RWPROT_SHIFT                              ST25DVXXKC_RFA2SS_RWPROT_SHIFT
#define ST25DV_RFA2SS_RWPROT_MASK                               ST25DVXXKC_RFA2SS_RWPROT_MASK
#define ST25DV_RFA2SS_RWPROT_FIELD                              ST25DVXXKC_RFA2SS_RWPROT_FIELD
#define ST25DV_RFA2SS_REG                                       ST25DVXXKC_RFA2SS_REG
#define ST25DV_RFA2SS_PWDCTRL_SHIFT                             ST25DVXXKC_RFA2SS_PWDCTRL_SHIFT
#define ST25DV_RFA2SS_PWDCTRL_MASK                              ST25DVXXKC_RFA2SS_PWDCTRL_MASK
#define ST25DV_RFA2SS_PWDCTRL_FIELD                             ST25DVXXKC_RFA2SS_PWDCTRL_FIELD
#define ST25DV_RFA2SS_ALL_SHIFT                                 ST25DVXXKC_RFA2SS_ALL_SHIFT
#define ST25DV_RFA2SS_ALL_MASK                                  ST25DVXXKC_RFA2SS_ALL_MASK
#define ST25DV_RFA1SS_RWPROT_SHIFT                              ST25DVXXKC_RFA1SS_RWPROT_SHIFT
#define ST25DV_RFA1SS_RWPROT_MASK                               ST25DVXXKC_RFA1SS_RWPROT_MASK
#define ST25DV_RFA1SS_RWPROT_FIELD                              ST25DVXXKC_RFA1SS_RWPROT_FIELD
#define ST25DV_RFA1SS_REG                                       ST25DVXXKC_RFA1SS_REG
#define ST25DV_RFA1SS_PWDCTRL_SHIFT                             ST25DVXXKC_RFA1SS_PWDCTRL_SHIFT
#define ST25DV_RFA1SS_PWDCTRL_MASK                              ST25DVXXKC_RFA1SS_PWDCTRL_MASK
#define ST25DV_RFA1SS_PWDCTRL_FIELD                             ST25DVXXKC_RFA1SS_PWDCTRL_FIELD
#define ST25DV_RFA1SS_ALL_SHIFT                                 ST25DVXXKC_RFA1SS_ALL_SHIFT
#define ST25DV_RFA1SS_ALL_MASK                                  ST25DVXXKC_RFA1SS_ALL_MASK
#define ST25DV_MEM_SIZE_MSB_REG                                 ST25DVXXKC_MEM_SIZE_MSB_REG
#define ST25DV_MEM_SIZE_LSB_REG                                 ST25DVXXKC_MEM_SIZE_LSB_REG
#define ST25DV_MB_WDG_DELAY_SHIFT                               ST25DVXXKC_FTM_MBWDG_SHIFT
#define ST25DV_MB_WDG_DELAY_MASK                                ST25DVXXKC_FTM_MBWDG_MASK
#define ST25DV_MB_WDG_DELAY_FIELD                               ST25DVXXKC_FTM_MBWDG_FIELD
#define ST25DV_MB_MODE_RW_SHIFT                                 ST25DVXXKC_FTM_MBMODE_SHIFT
#define ST25DV_MB_MODE_RW_MASK                                  ST25DVXXKC_FTM_MBMODE_MASK
#define ST25DV_MB_MODE_RW_FIELD                                 ST25DVXXKC_FTM_MBMODE_FIELD
#define ST25DV_MB_CTRL_DYN_STRESERVED_SHIFT                     ST25DVXXKC_MB_CTRL_DYN_STRESERVED_SHIFT
#define ST25DV_MB_CTRL_DYN_STRESERVED_MASK                      ST25DVXXKC_MB_CTRL_DYN_STRESERVED_MASK
#define ST25DV_MB_CTRL_DYN_STRESERVED_FIELD                     ST25DVXXKC_MB_CTRL_DYN_STRESERVED_FIELD
#define ST25DV_MB_CTRL_DYN_RFPUTMSG_SHIFT                       ST25DVXXKC_MB_CTRL_DYN_RFPUTMSG_SHIFT
#define ST25DV_MB_CTRL_DYN_RFPUTMSG_MASK                        ST25DVXXKC_MB_CTRL_DYN_RFPUTMSG_MASK
#define ST25DV_MB_CTRL_DYN_RFPUTMSG_FIELD                       ST25DVXXKC_MB_CTRL_DYN_RFPUTMSG_FIELD
#define ST25DV_MB_CTRL_DYN_RFMISSMSG_SHIFT                      ST25DVXXKC_MB_CTRL_DYN_RFMISSMSG_SHIFT
#define ST25DV_MB_CTRL_DYN_RFMISSMSG_MASK                       ST25DVXXKC_MB_CTRL_DYN_RFMISSMSG_MASK
#define ST25DV_MB_CTRL_DYN_RFMISSMSG_FIELD                      ST25DVXXKC_MB_CTRL_DYN_RFMISSMSG_FIELD
#define ST25DV_MB_CTRL_DYN_REG                                  ST25DVXXKC_MB_CTRL_DYN_REG
#define ST25DV_MB_CTRL_DYN_MBEN_SHIFT                           ST25DVXXKC_MB_CTRL_DYN_MBEN_SHIFT
#define ST25DV_MB_CTRL_DYN_MBEN_MASK                            ST25DVXXKC_MB_CTRL_DYN_MBEN_MASK
#define ST25DV_MB_CTRL_DYN_MBEN_FIELD                           ST25DVXXKC_MB_CTRL_DYN_MBEN_FIELD
#define ST25DV_MB_CTRL_DYN_HOSTPUTMSG_SHIFT                     ST25DVXXKC_MB_CTRL_DYN_HOSTPUTMSG_SHIFT
#define ST25DV_MB_CTRL_DYN_HOSTPUTMSG_MASK                      ST25DVXXKC_MB_CTRL_DYN_HOSTPUTMSG_MASK
#define ST25DV_MB_CTRL_DYN_HOSTPUTMSG_FIELD                     ST25DVXXKC_MB_CTRL_DYN_HOSTPUTMSG_FIELD
#define ST25DV_MB_CTRL_DYN_HOSTMISSMSG_SHIFT                    ST25DVXXKC_MB_CTRL_DYN_HOSTMISSMSG_SHIFT
#define ST25DV_MB_CTRL_DYN_HOSTMISSMSG_MASK                     ST25DVXXKC_MB_CTRL_DYN_HOSTMISSMSG_MASK
#define ST25DV_MB_CTRL_DYN_HOSTMISSMSG_FIELD                    ST25DVXXKC_MB_CTRL_DYN_HOSTMISSMSG_FIELD
#define ST25DV_MB_CTRL_DYN_CURRENTMSG_SHIFT                     ST25DVXXKC_MB_CTRL_DYN_CURRENTMSG_SHIFT
#define ST25DV_MB_CTRL_DYN_CURRENTMSG_MASK                      ST25DVXXKC_MB_CTRL_DYN_CURRENTMSG_MASK
#define ST25DV_MB_CTRL_DYN_CURRENTMSG_FIELD                     ST25DVXXKC_MB_CTRL_DYN_CURRENTMSG_FIELD
#define ST25DV_MBLEN_DYN_REG                                    ST25DVXXKC_MBLEN_DYN_REG
#define ST25DV_MBLEN_DYN_MBLEN_SHIFT                            ST25DVXXKC_MBLEN_DYN_MBLEN_SHIFT
#define ST25DV_MBLEN_DYN_MBLEN_MASK                             ST25DVXXKC_MBLEN_DYN_MBLEN_MASK
#define ST25DV_MBLEN_DYN_MBLEN_FIELD                            ST25DVXXKC_MBLEN_DYN_MBLEN_FIELD
#define ST25DV_MAILBOX_RAM_REG                                  ST25DVXXKC_MAILBOX_RAM_REG
#define ST25DV_LOCKDSFID_REG                                    ST25DVXXKC_LOCKDSFID_REG
#define ST25DV_LOCKCFG_REG                                      ST25DVXXKC_LOCKCFG_REG
#define ST25DV_LOCKCFG_B0_SHIFT                                 ST25DVXXKC_LOCKCFG_B0_SHIFT
#define ST25DV_LOCKCFG_B0_MASK                                  ST25DVXXKC_LOCKCFG_B0_MASK
#define ST25DV_LOCKCFG_B0_FIELD                                 ST25DVXXKC_LOCKCFG_B0_FIELD
#define ST25DV_LOCKCCFILE_REG                                   ST25DVXXKC_LOCKCCFILE_REG
#define ST25DV_LOCKCCFILE_BLCK1_SHIFT                           ST25DVXXKC_LOCKCCFILE_BLCK1_SHIFT
#define ST25DV_LOCKCCFILE_BLCK1_MASK                            ST25DVXXKC_LOCKCCFILE_BLCK1_MASK
#define ST25DV_LOCKCCFILE_BLCK1_FIELD                           ST25DVXXKC_LOCKCCFILE_BLCK1_FIELD
#define ST25DV_LOCKCCFILE_BLCK0_SHIFT                           ST25DVXXKC_LOCKCCFILE_BLCK0_SHIFT
#define ST25DV_LOCKCCFILE_BLCK0_MASK                            ST25DVXXKC_LOCKCCFILE_BLCK0_MASK
#define ST25DV_LOCKCCFILE_BLCK0_FIELD                           ST25DVXXKC_LOCKCCFILE_BLCK0_FIELD
#define ST25DV_LOCKCCFILE_ALL_SHIFT                             ST25DVXXKC_LOCKCCFILE_ALL_SHIFT
#define ST25DV_LOCKCCFILE_ALL_MASK                              ST25DVXXKC_LOCKCCFILE_ALL_MASK
#define ST25DV_LOCKAFI_REG                                      ST25DVXXKC_LOCKAFI_REG
#define ST25DV_ITSTS_DYN_RFWRITE_SHIFT                          ST25DVXXKC_ITSTS_DYN_RFWRITE_SHIFT
#define ST25DV_ITSTS_DYN_RFWRITE_MASK                           ST25DVXXKC_ITSTS_DYN_RFWRITE_MASK
#define ST25DV_ITSTS_DYN_RFWRITE_FIELD                          ST25DVXXKC_ITSTS_DYN_RFWRITE_FIELD
#define ST25DV_ITSTS_DYN_RFUSERSTATE_SHIFT                      ST25DVXXKC_ITSTS_DYN_RFUSERSTATE_SHIFT
#define ST25DV_ITSTS_DYN_RFUSERSTATE_MASK                       ST25DVXXKC_ITSTS_DYN_RFUSERSTATE_MASK
#define ST25DV_ITSTS_DYN_RFUSERSTATE_FIELD                      ST25DVXXKC_ITSTS_DYN_RFUSERSTATE_FIELD
#define ST25DV_ITSTS_DYN_RFPUTMSG_SHIFT                         ST25DVXXKC_ITSTS_DYN_RFPUTMSG_SHIFT
#define ST25DV_ITSTS_DYN_RFPUTMSG_MASK                          ST25DVXXKC_ITSTS_DYN_RFPUTMSG_MASK
#define ST25DV_ITSTS_DYN_RFPUTMSG_FIELD                         ST25DVXXKC_ITSTS_DYN_RFPUTMSG_FIELD
#define ST25DV_ITSTS_DYN_RFINTERRUPT_SHIFT                      ST25DVXXKC_ITSTS_DYN_RFINTERRUPT_SHIFT
#define ST25DV_ITSTS_DYN_RFINTERRUPT_MASK                       ST25DVXXKC_ITSTS_DYN_RFINTERRUPT_MASK
#define ST25DV_ITSTS_DYN_RFINTERRUPT_FIELD                      ST25DVXXKC_ITSTS_DYN_RFINTERRUPT_FIELD
#define ST25DV_ITSTS_DYN_RFGETMSG_SHIFT                         ST25DVXXKC_ITSTS_DYN_RFGETMSG_SHIFT
#define ST25DV_ITSTS_DYN_RFGETMSG_MASK                          ST25DVXXKC_ITSTS_DYN_RFGETMSG_MASK
#define ST25DV_ITSTS_DYN_RFGETMSG_FIELD                         ST25DVXXKC_ITSTS_DYN_RFGETMSG_FIELD
#define ST25DV_ITSTS_DYN_RFACTIVITY_SHIFT                       ST25DVXXKC_ITSTS_DYN_RFACTIVITY_SHIFT
#define ST25DV_ITSTS_DYN_RFACTIVITY_MASK                        ST25DVXXKC_ITSTS_DYN_RFACTIVITY_MASK
#define ST25DV_ITSTS_DYN_RFACTIVITY_FIELD                       ST25DVXXKC_ITSTS_DYN_RFACTIVITY_FIELD
#define ST25DV_ITSTS_DYN_REG                                    ST25DVXXKC_ITSTS_DYN_REG
#define ST25DV_ITSTS_DYN_FIELDRISING_SHIFT                      ST25DVXXKC_ITSTS_DYN_FIELDRISING_SHIFT
#define ST25DV_ITSTS_DYN_FIELDRISING_MASK                       ST25DVXXKC_ITSTS_DYN_FIELDRISING_MASK
#define ST25DV_ITSTS_DYN_FIELDRISING_FIELD                      ST25DVXXKC_ITSTS_DYN_FIELDRISING_FIELD
#define ST25DV_ITSTS_DYN_FIELDFALLING_SHIFT                     ST25DVXXKC_ITSTS_DYN_FIELDFALLING_SHIFT
#define ST25DV_ITSTS_DYN_FIELDFALLING_MASK                      ST25DVXXKC_ITSTS_DYN_FIELDFALLING_MASK
#define ST25DV_ITSTS_DYN_FIELDFALLING_FIELD                     ST25DVXXKC_ITSTS_DYN_FIELDFALLING_FIELD
#define ST25DV_ICREV_REG                                        ST25DVXXKC_ICREV_REG
#define ST25DV_ICREF_REG                                        ST25DVXXKC_ICREF_REG
#define ST25DV_I2C_SSO_DYN_REG                                  ST25DVXXKC_I2C_SSO_DYN_REG
#define ST25DV_I2C_SSO_DYN_I2CSSO_SHIFT                         ST25DVXXKC_I2C_SSO_DYN_I2CSSO_SHIFT
#define ST25DV_I2C_SSO_DYN_I2CSSO_MASK                          ST25DVXXKC_I2C_SSO_DYN_I2CSSO_MASK
#define ST25DV_I2C_SSO_DYN_I2CSSO_FIELD                         ST25DVXXKC_I2C_SSO_DYN_I2CSSO_FIELD
#define ST25DV_I2CSS_REG                                        ST25DVXXKC_I2CSS_REG
#define ST25DV_I2CSS_PZ4_SHIFT                                  ST25DVXXKC_I2CSS_PZ4_SHIFT
#define ST25DV_I2CSS_PZ4_MASK                                   ST25DVXXKC_I2CSS_PZ4_MASK
#define ST25DV_I2CSS_PZ4_FIELD                                  ST25DVXXKC_I2CSS_PZ4_FIELD
#define ST25DV_I2CSS_PZ3_SHIFT                                  ST25DVXXKC_I2CSS_PZ3_SHIFT
#define ST25DV_I2CSS_PZ3_MASK                                   ST25DVXXKC_I2CSS_PZ3_MASK
#define ST25DV_I2CSS_PZ3_FIELD                                  ST25DVXXKC_I2CSS_PZ3_FIELD
#define ST25DV_I2CSS_PZ2_SHIFT                                  ST25DVXXKC_I2CSS_PZ2_SHIFT
#define ST25DV_I2CSS_PZ2_MASK                                   ST25DVXXKC_I2CSS_PZ2_MASK
#define ST25DV_I2CSS_PZ2_FIELD                                  ST25DVXXKC_I2CSS_PZ2_FIELD
#define ST25DV_I2CSS_PZ1_SHIFT                                  ST25DVXXKC_I2CSS_PZ1_SHIFT
#define ST25DV_I2CSS_PZ1_MASK                                   ST25DVXXKC_I2CSS_PZ1_MASK
#define ST25DV_I2CSS_PZ1_FIELD                                  ST25DVXXKC_I2CSS_PZ1_FIELD
#define ST25DV_I2CPASSWD_REG                                    ST25DVXXKC_I2CPASSWD_REG
#define ST25DV_GPO_RFWRITE_SHIFT                                ST25DVXXKC_GPO1_RFWRITE_SHIFT
#define ST25DV_GPO_RFWRITE_MASK                                 ST25DVXXKC_GPO1_RFWRITE_MASK
#define ST25DV_GPO_RFWRITE_FIELD                                ST25DVXXKC_GPO1_RFWRITE_FIELD
#define ST25DV_GPO_RFUSERSTATE_SHIFT                            ST25DVXXKC_GPO1_RFUSERSTATE_SHIFT
#define ST25DV_GPO_RFUSERSTATE_MASK                             ST25DVXXKC_GPO1_RFUSERSTATE_MASK
#define ST25DV_GPO_RFUSERSTATE_FIELD                            ST25DVXXKC_GPO1_RFUSERSTATE_FIELD
#define ST25DV_GPO_RFPUTMSG_SHIFT                               ST25DVXXKC_GPO1_RFPUTMSG_SHIFT
#define ST25DV_GPO_RFPUTMSG_MASK                                ST25DVXXKC_GPO1_RFPUTMSG_MASK
#define ST25DV_GPO_RFPUTMSG_FIELD                               ST25DVXXKC_GPO1_RFPUTMSG_FIELD
#define ST25DV_GPO_RFINTERRUPT_SHIFT                            ST25DVXXKC_GPO1_RFINTERRUPT_SHIFT
#define ST25DV_GPO_RFINTERRUPT_MASK                             ST25DVXXKC_GPO1_RFINTERRUPT_MASK
#define ST25DV_GPO_RFINTERRUPT_FIELD                            ST25DVXXKC_GPO1_RFINTERRUPT_FIELD
#define ST25DV_GPO_RFGETMSG_SHIFT                               ST25DVXXKC_GPO1_RFGETMSG_SHIFT
#define ST25DV_GPO_RFGETMSG_MASK                                ST25DVXXKC_GPO1_RFGETMSG_MASK
#define ST25DV_GPO_RFGETMSG_FIELD                               ST25DVXXKC_GPO1_RFGETMSG_FIELD
#define ST25DV_GPO_RFACTIVITY_SHIFT                             ST25DVXXKC_GPO1_RFACTIVITY_SHIFT
#define ST25DV_GPO_RFACTIVITY_MASK                              ST25DVXXKC_GPO1_RFACTIVITY_MASK
#define ST25DV_GPO_RFACTIVITY_FIELD                             ST25DVXXKC_GPO1_RFACTIVITY_FIELD
#define ST25DV_GPO_FIELDCHANGE_SHIFT                            ST25DVXXKC_GPO1_FIELDCHANGE_SHIFT
#define ST25DV_GPO_FIELDCHANGE_MASK                             ST25DVXXKC_GPO1_FIELDCHANGE_MASK
#define ST25DV_GPO_FIELDCHANGE_FIELD                            ST25DVXXKC_GPO1_FIELDCHANGE_FIELD
#define ST25DV_GPO_ENABLE_SHIFT                                 ST25DVXXKC_GPO1_ENABLE_SHIFT
#define ST25DV_GPO_ENABLE_MASK                                  ST25DVXXKC_GPO1_ENABLE_MASK
#define ST25DV_GPO_ENABLE_FIELD                                 ST25DVXXKC_GPO1_ENABLE_FIELD
#define ST25DV_GPO_ALL_SHIFT                                    ST25DVXXKC_GPO1_ALL_SHIFT
#define ST25DV_GPO_ALL_MASK                                     ST25DVXXKC_GPO1_ALL_MASK
#define ST25DV_GPO_DYN_RFWRITE_SHIFT                            ST25DVXXKC_GPO1_RFWRITE_SHIFT       // Map on GPO1 register as most of GPO_DYN entries are no more available
#define ST25DV_GPO_DYN_RFWRITE_MASK                             ST25DVXXKC_GPO1_RFWRITE_MASK
#define ST25DV_GPO_DYN_RFWRITE_FIELD                            ST25DVXXKC_GPO1_RFWRITE_FIELD
#define ST25DV_GPO_DYN_RFUSERSTATE_SHIFT                        ST25DVXXKC_GPO1_RFUSERSTATE_SHIFT
#define ST25DV_GPO_DYN_RFUSERSTATE_MASK                         ST25DVXXKC_GPO1_RFUSERSTATE_MASK
#define ST25DV_GPO_DYN_RFUSERSTATE_FIELD                        ST25DVXXKC_GPO1_RFUSERSTATE_FIELD
#define ST25DV_GPO_DYN_RFPUTMSG_SHIFT                           ST25DVXXKC_GPO1_RFPUTMSG_SHIFT
#define ST25DV_GPO_DYN_RFPUTMSG_MASK                            ST25DVXXKC_GPO1_RFPUTMSG_MASK
#define ST25DV_GPO_DYN_RFPUTMSG_FIELD                           ST25DVXXKC_GPO1_RFPUTMSG_FIELD
#define ST25DV_GPO_DYN_RFINTERRUPT_SHIFT                        ST25DVXXKC_GPO1_RFINTERRUPT_SHIFT
#define ST25DV_GPO_DYN_RFINTERRUPT_MASK                         ST25DVXXKC_GPO1_RFINTERRUPT_MASK
#define ST25DV_GPO_DYN_RFINTERRUPT_FIELD                        ST25DVXXKC_GPO1_RFINTERRUPT_FIELD
#define ST25DV_GPO_DYN_RFGETMSG_SHIFT                           ST25DVXXKC_GPO1_RFGETMSG_SHIFT
#define ST25DV_GPO_DYN_RFGETMSG_MASK                            ST25DVXXKC_GPO1_RFGETMSG_MASK
#define ST25DV_GPO_DYN_RFGETMSG_FIELD                           ST25DVXXKC_GPO1_RFGETMSG_FIELD
#define ST25DV_GPO_DYN_RFACTIVITY_SHIFT                         ST25DVXXKC_GPO1_RFACTIVITY_SHIFT
#define ST25DV_GPO_DYN_RFACTIVITY_MASK                          ST25DVXXKC_GPO1_RFACTIVITY_MASK
#define ST25DV_GPO_DYN_RFACTIVITY_FIELD                         ST25DVXXKC_GPO1_RFACTIVITY_FIELD
#define ST25DV_GPO_DYN_REG                                      ST25DVXXKC_GPO_DYN_REG
#define ST25DV_GPO_DYN_ENABLE_SHIFT                             ST25DVXXKC_GPO_DYN_ENABLE_SHIFT
#define ST25DV_GPO_DYN_ENABLE_MASK                              ST25DVXXKC_GPO_DYN_ENABLE_MASK
#define ST25DV_GPO_DYN_ENABLE_FIELD                             ST25DVXXKC_GPO_DYN_ENABLE_FIELD
#define ST25DV_GPO_DYN_ALL_SHIFT                                ST25DVXXKC_GPO_DYN_ALL_SHIFT
#define ST25DV_GPO_DYN_ALL_MASK                                 ST25DVXXKC_GPO_DYN_ALL_MASK
#define ST25DV_ENDA3_REG                                        ST25DVXXKC_ENDA3_REG
#define ST25DV_ENDA2_REG                                        ST25DVXXKC_ENDA2_REG
#define ST25DV_ENDA1_REG                                        ST25DVXXKC_ENDA1_REG
#define ST25DV_EH_MODE_SHIFT                                    ST25DVXXKC_EH_MODE_SHIFT
#define ST25DV_EH_MODE_REG                                      ST25DVXXKC_EH_MODE_REG
#define ST25DV_EH_MODE_MASK                                     ST25DVXXKC_EH_MODE_MASK
#define ST25DV_EH_MODE_FIELD                                    ST25DVXXKC_EH_MODE_FIELD
#define ST25DV_EH_CTRL_DYN_VCC_ON_SHIFT                         ST25DVXXKC_EH_CTRL_DYN_VCC_ON_SHIFT
#define ST25DV_EH_CTRL_DYN_VCC_ON_MASK                          ST25DVXXKC_EH_CTRL_DYN_VCC_ON_MASK
#define ST25DV_EH_CTRL_DYN_VCC_ON_FIELD                         ST25DVXXKC_EH_CTRL_DYN_VCC_ON_FIELD
#define ST25DV_EH_CTRL_DYN_REG                                  ST25DVXXKC_EH_CTRL_DYN_REG
#define ST25DV_EH_CTRL_DYN_FIELD_ON_SHIFT                       ST25DVXXKC_EH_CTRL_DYN_FIELD_ON_SHIFT
#define ST25DV_EH_CTRL_DYN_FIELD_ON_MASK                        ST25DVXXKC_EH_CTRL_DYN_FIELD_ON_MASK
#define ST25DV_EH_CTRL_DYN_FIELD_ON_FIELD                       ST25DVXXKC_EH_CTRL_DYN_FIELD_ON_FIELD
#define ST25DV_EH_CTRL_DYN_EH_ON_SHIFT                          ST25DVXXKC_EH_CTRL_DYN_EH_ON_SHIFT
#define ST25DV_EH_CTRL_DYN_EH_ON_MASK                           ST25DVXXKC_EH_CTRL_DYN_EH_ON_MASK
#define ST25DV_EH_CTRL_DYN_EH_ON_FIELD                          ST25DVXXKC_EH_CTRL_DYN_EH_ON_FIELD
#define ST25DV_EH_CTRL_DYN_EH_EN_SHIFT                          ST25DVXXKC_EH_CTRL_DYN_EH_EN_SHIFT
#define ST25DV_EH_CTRL_DYN_EH_EN_MASK                           ST25DVXXKC_EH_CTRL_DYN_EH_EN_MASK
#define ST25DV_EH_CTRL_DYN_EH_EN_FIELD                          ST25DVXXKC_EH_CTRL_DYN_EH_EN_FIELD
#define ST25DV_EH_CTRL_DYN_ALL_SHIFT                            ST25DVXXKC_EH_CTRL_DYN_ALL_SHIFT
#define ST25DV_EH_CTRL_DYN_ALL_MASK                             ST25DVXXKC_EH_CTRL_DYN_ALL_MASK
#define ST25DV_DSFID_REG                                        ST25DVXXKC_DSFID_REG
#define ST25DV_Ctx_t                                            ST25DVxxKC_Ctx_t
#define ST25DV_BLK_SIZE_REG                                     ST25DVXXKC_BLK_SIZE_REG
#define ST25DV_AFI_REG                                          ST25DVXXKC_AFI_REG
#define ST25DV_MB_WDG_REG                                       ST25DVXXKC_I2CCFG_REG
#define ST25DV_MB_MODE_REG                                      ST25DVXXKC_FTM_REG
#define ST25DV_ITTIME_REG                                       ST25DVXXKC_GPO2_REG
#define ST25DV_ITTIME_DELAY_SHIFT                               ST25DVXXKC_GPO2_ITTIME_SHIFT
#define ST25DV_ITTIME_DELAY_MASK                                ST25DVXXKC_GPO2_ITTIME_MASK
#define ST25DV_ITTIME_DELAY_FIELD                               ST25DVXXKC_GPO2_ITTIME_FIELD
#define ST25DV_GPO_REG                                          ST25DVXXKC_GPO1_REG
#define ST25DV_GPO_DYN_FIELDCHANGE_SHIFT                        ST25DVXXKC_GPO1_FIELDCHANGE_SHIFT
#define ST25DV_GPO_DYN_FIELDCHANGE_MASK                         ST25DVXXKC_GPO1_FIELDCHANGE_MASK
#define ST25DV_GPO_DYN_FIELDCHANGE_FIELD                        ST25DVXXKC_GPO1_FIELDCHANGE_FIELD

#define ST25DV_GetICREF                                         ST25DVxxKC_GetICREF 
#define ST25DV_GetENDA1                                         ST25DVxxKC_GetENDA1 
#define ST25DV_SetENDA1                                         ST25DVxxKC_SetENDA1 
#define ST25DV_GetENDA2                                         ST25DVxxKC_GetENDA2 
#define ST25DV_SetENDA2                                         ST25DVxxKC_SetENDA2 
#define ST25DV_GetENDA3                                         ST25DVxxKC_GetENDA3 
#define ST25DV_SetENDA3                                         ST25DVxxKC_SetENDA3 
#define ST25DV_GetDSFID                                         ST25DVxxKC_GetDSFID 
#define ST25DV_GetAFI                                           ST25DVxxKC_GetAFI 
#define ST25DV_GetMEM_SIZE_MSB                                  ST25DVxxKC_GetMEM_SIZE_MSB 
#define ST25DV_GetBLK_SIZE                                      ST25DVxxKC_GetBLK_SIZE 
#define ST25DV_GetMEM_SIZE_LSB                                  ST25DVxxKC_GetMEM_SIZE_LSB 
#define ST25DV_GetICREV                                         ST25DVxxKC_GetICREV 
#define ST25DV_GetUID                                           ST25DVxxKC_GetUID 
#define ST25DV_GetI2CPASSWD                                     ST25DVxxKC_GetI2CPASSWD 
#define ST25DV_SetI2CPASSWD                                     ST25DVxxKC_SetI2CPASSWD 
#define ST25DV_GetLOCKDSFID                                     ST25DVxxKC_GetLOCKDSFID 
#define ST25DV_GetLOCKAFI                                       ST25DVxxKC_GetLOCKAFI 
#define ST25DV_GetMB_MODE_RW                                    ST25DVxxKC_GetFTM_MBMODE 
#define ST25DV_SetMB_MODE_RW                                    ST25DVxxKC_SetFTM_MBMODE 
#define ST25DV_GetMBLEN_DYN_MBLEN                               ST25DVxxKC_GetMBLEN_DYN_MBLEN 
#define ST25DV_GetMB_CTRL_DYN_MBEN                              ST25DVxxKC_GetMB_CTRL_DYN_MBEN 
#define ST25DV_SetMB_CTRL_DYN_MBEN                              ST25DVxxKC_SetMB_CTRL_DYN_MBEN 
#define ST25DV_GetMB_CTRL_DYN_HOSTPUTMSG                        ST25DVxxKC_GetMB_CTRL_DYN_HOSTPUTMSG 
#define ST25DV_GetMB_CTRL_DYN_RFPUTMSG                          ST25DVxxKC_GetMB_CTRL_DYN_RFPUTMSG 
#define ST25DV_GetMB_CTRL_DYN_STRESERVED                        ST25DVxxKC_GetMB_CTRL_DYN_STRESERVED 
#define ST25DV_GetMB_CTRL_DYN_HOSTMISSMSG                       ST25DVxxKC_GetMB_CTRL_DYN_HOSTMISSMSG 
#define ST25DV_GetMB_CTRL_DYN_RFMISSMSG                         ST25DVxxKC_GetMB_CTRL_DYN_RFMISSMSG 
#define ST25DV_GetMB_CTRL_DYN_CURRENTMSG                        ST25DVxxKC_GetMB_CTRL_DYN_CURRENTMSG 
#define ST25DV_GetMB_CTRL_DYN_ALL                               ST25DVxxKC_GetMB_CTRL_DYN_ALL 
#define ST25DV_GetMB_WDG_DELAY                                  ST25DVxxKC_GetFTM_MBWDG 
#define ST25DV_SetMB_WDG_DELAY                                  ST25DVxxKC_SetFTM_MBWDG 
#define ST25DV_GetGPO_RFUSERSTATE                               ST25DVxxKC_GetGPO_RFUSERSTATE 
#define ST25DV_SetGPO_RFUSERSTATE                               ST25DVxxKC_SetGPO_RFUSERSTATE 
#define ST25DV_GetGPO_RFACTIVITY                                ST25DVxxKC_GetGPO_RFACTIVITY 
#define ST25DV_SetGPO_RFACTIVITY                                ST25DVxxKC_SetGPO_RFACTIVITY 
#define ST25DV_GetGPO_RFINTERRUPT                               ST25DVxxKC_GetGPO_RFINTERRUPT 
#define ST25DV_SetGPO_RFINTERRUPT                               ST25DVxxKC_SetGPO_RFINTERRUPT 
#define ST25DV_GetGPO_FIELDCHANGE                               ST25DVxxKC_GetGPO_FIELDCHANGE 
#define ST25DV_SetGPO_FIELDCHANGE                               ST25DVxxKC_SetGPO_FIELDCHANGE 
#define ST25DV_GetGPO_RFPUTMSG                                  ST25DVxxKC_GetGPO_RFPUTMSG 
#define ST25DV_SetGPO_RFPUTMSG                                  ST25DVxxKC_SetGPO_RFPUTMSG 
#define ST25DV_GetGPO_RFGETMSG                                  ST25DVxxKC_GetGPO_RFGETMSG 
#define ST25DV_SetGPO_RFGETMSG                                  ST25DVxxKC_SetGPO_RFGETMSG 
#define ST25DV_GetGPO_RFWRITE                                   ST25DVxxKC_GetGPO_RFWRITE 
#define ST25DV_SetGPO_RFWRITE                                   ST25DVxxKC_SetGPO_RFWRITE 
#define ST25DV_GetGPO_ENABLE                                    ST25DVxxKC_GetGPO_ENABLE 
#define ST25DV_SetGPO_ENABLE                                    ST25DVxxKC_SetGPO_ENABLE 
#define ST25DV_GetGPO_ALL                                       ST25DVxxKC_GetGPO_ALL 
#define ST25DV_SetGPO_ALL                                       ST25DVxxKC_SetGPO_ALL 
#define ST25DV_GetGPO_DYN_RFUSERSTATE                           ST25DVxxKC_GetGPO_DYN_RFUSERSTATE 
#define ST25DV_SetGPO_DYN_RFUSERSTATE                           ST25DVxxKC_SetGPO_DYN_RFUSERSTATE 
#define ST25DV_GetGPO_DYN_RFACTIVITY                            ST25DVxxKC_GetGPO_DYN_RFACTIVITY 
#define ST25DV_SetGPO_DYN_RFACTIVITY                            ST25DVxxKC_SetGPO_DYN_RFACTIVITY 
#define ST25DV_GetGPO_DYN_RFINTERRUPT                           ST25DVxxKC_GetGPO_DYN_RFINTERRUPT 
#define ST25DV_SetGPO_DYN_RFINTERRUPT                           ST25DVxxKC_SetGPO_DYN_RFINTERRUPT 
#define ST25DV_GetGPO_DYN_FIELDCHANGE                           ST25DVxxKC_GetGPO_DYN_FIELDCHANGE 
#define ST25DV_SetGPO_DYN_FIELDCHANGE                           ST25DVxxKC_SetGPO_DYN_FIELDCHANGE 
#define ST25DV_GetGPO_DYN_RFPUTMSG                              ST25DVxxKC_GetGPO_DYN_RFPUTMSG 
#define ST25DV_SetGPO_DYN_RFPUTMSG                              ST25DVxxKC_SetGPO_DYN_RFPUTMSG 
#define ST25DV_GetGPO_DYN_RFGETMSG                              ST25DVxxKC_GetGPO_DYN_RFGETMSG 
#define ST25DV_SetGPO_DYN_RFGETMSG                              ST25DVxxKC_SetGPO_DYN_RFGETMSG 
#define ST25DV_GetGPO_DYN_RFWRITE                               ST25DVxxKC_GetGPO_DYN_RFWRITE 
#define ST25DV_SetGPO_DYN_RFWRITE                               ST25DVxxKC_SetGPO_DYN_RFWRITE 
#define ST25DV_GetGPO_DYN_ENABLE                                ST25DVxxKC_GetGPO_DYN_ENABLE 
#define ST25DV_SetGPO_DYN_ENABLE                                ST25DVxxKC_SetGPO_DYN_ENABLE 
#define ST25DV_GetGPO_DYN_ALL                                   ST25DVxxKC_GetGPO_DYN_ALL 
#define ST25DV_SetGPO_DYN_ALL                                   ST25DVxxKC_SetGPO_DYN_ALL 
#define ST25DV_GetITTIME_DELAY                                  ST25DVxxKC_GetITTIME_DELAY 
#define ST25DV_SetITTIME_DELAY                                  ST25DVxxKC_SetITTIME_DELAY 
#define ST25DV_GetITSTS_DYN_RFUSERSTATE                         ST25DVxxKC_GetITSTS_DYN_RFUSERSTATE 
#define ST25DV_GetITSTS_DYN_RFACTIVITY                          ST25DVxxKC_GetITSTS_DYN_RFACTIVITY 
#define ST25DV_GetITSTS_DYN_RFINTERRUPT                         ST25DVxxKC_GetITSTS_DYN_RFINTERRUPT 
#define ST25DV_GetITSTS_DYN_FIELDFALLING                        ST25DVxxKC_GetITSTS_DYN_FIELDFALLING 
#define ST25DV_GetITSTS_DYN_FIELDRISING                         ST25DVxxKC_GetITSTS_DYN_FIELDRISING 
#define ST25DV_GetITSTS_DYN_RFPUTMSG                            ST25DVxxKC_GetITSTS_DYN_RFPUTMSG 
#define ST25DV_GetITSTS_DYN_RFGETMSG                            ST25DVxxKC_GetITSTS_DYN_RFGETMSG 
#define ST25DV_GetITSTS_DYN_RFWRITE                             ST25DVxxKC_GetITSTS_DYN_RFWRITE 
#define ST25DV_GetITSTS_DYN_ALL                                 ST25DVxxKC_GetITSTS_DYN_ALL 
#define ST25DV_GetEH_MODE                                       ST25DVxxKC_GetEH_MODE 
#define ST25DV_SetEH_MODE                                       ST25DVxxKC_SetEH_MODE 
#define ST25DV_GetEH_CTRL_DYN_EH_EN                             ST25DVxxKC_GetEH_CTRL_DYN_EH_EN 
#define ST25DV_SetEH_CTRL_DYN_EH_EN                             ST25DVxxKC_SetEH_CTRL_DYN_EH_EN 
#define ST25DV_GetEH_CTRL_DYN_EH_ON                             ST25DVxxKC_GetEH_CTRL_DYN_EH_ON 
#define ST25DV_GetEH_CTRL_DYN_FIELD_ON                          ST25DVxxKC_GetEH_CTRL_DYN_FIELD_ON 
#define ST25DV_GetEH_CTRL_DYN_VCC_ON                            ST25DVxxKC_GetEH_CTRL_DYN_VCC_ON 
#define ST25DV_GetEH_CTRL_DYN_ALL                               ST25DVxxKC_GetEH_CTRL_DYN_ALL 
#define ST25DV_GetRF_MNGT_RFDIS                                 ST25DVxxKC_GetRF_MNGT_RFDIS 
#define ST25DV_SetRF_MNGT_RFDIS                                 ST25DVxxKC_SetRF_MNGT_RFDIS 
#define ST25DV_GetRF_MNGT_RFSLEEP                               ST25DVxxKC_GetRF_MNGT_RFSLEEP 
#define ST25DV_SetRF_MNGT_RFSLEEP                               ST25DVxxKC_SetRF_MNGT_RFSLEEP 
#define ST25DV_GetRF_MNGT_ALL                                   ST25DVxxKC_GetRF_MNGT_ALL 
#define ST25DV_SetRF_MNGT_ALL                                   ST25DVxxKC_SetRF_MNGT_ALL 
#define ST25DV_GetRF_MNGT_DYN_RFDIS                             ST25DVxxKC_GetRF_MNGT_DYN_RFDIS 
#define ST25DV_SetRF_MNGT_DYN_RFDIS                             ST25DVxxKC_SetRF_MNGT_DYN_RFDIS 
#define ST25DV_GetRF_MNGT_DYN_RFSLEEP                           ST25DVxxKC_GetRF_MNGT_DYN_RFSLEEP 
#define ST25DV_SetRF_MNGT_DYN_RFSLEEP                           ST25DVxxKC_SetRF_MNGT_DYN_RFSLEEP 
#define ST25DV_GetRF_MNGT_DYN_ALL                               ST25DVxxKC_GetRF_MNGT_DYN_ALL 
#define ST25DV_SetRF_MNGT_DYN_ALL                               ST25DVxxKC_SetRF_MNGT_DYN_ALL 
#define ST25DV_GetRFA1SS_PWDCTRL                                ST25DVxxKC_GetRFA1SS_PWDCTRL 
#define ST25DV_SetRFA1SS_PWDCTRL                                ST25DVxxKC_SetRFA1SS_PWDCTRL 
#define ST25DV_GetRFA1SS_RWPROT                                 ST25DVxxKC_GetRFA1SS_RWPROT 
#define ST25DV_SetRFA1SS_RWPROT                                 ST25DVxxKC_SetRFA1SS_RWPROT 
#define ST25DV_GetRFA1SS_ALL                                    ST25DVxxKC_GetRFA1SS_ALL 
#define ST25DV_SetRFA1SS_ALL                                    ST25DVxxKC_SetRFA1SS_ALL 
#define ST25DV_GetRFA2SS_PWDCTRL                                ST25DVxxKC_GetRFA2SS_PWDCTRL 
#define ST25DV_SetRFA2SS_PWDCTRL                                ST25DVxxKC_SetRFA2SS_PWDCTRL 
#define ST25DV_GetRFA2SS_RWPROT                                 ST25DVxxKC_GetRFA2SS_RWPROT 
#define ST25DV_SetRFA2SS_RWPROT                                 ST25DVxxKC_SetRFA2SS_RWPROT 
#define ST25DV_GetRFA2SS_ALL                                    ST25DVxxKC_GetRFA2SS_ALL 
#define ST25DV_SetRFA2SS_ALL                                    ST25DVxxKC_SetRFA2SS_ALL 
#define ST25DV_GetRFA3SS_PWDCTRL                                ST25DVxxKC_GetRFA3SS_PWDCTRL 
#define ST25DV_SetRFA3SS_PWDCTRL                                ST25DVxxKC_SetRFA3SS_PWDCTRL 
#define ST25DV_GetRFA3SS_RWPROT                                 ST25DVxxKC_GetRFA3SS_RWPROT 
#define ST25DV_SetRFA3SS_RWPROT                                 ST25DVxxKC_SetRFA3SS_RWPROT 
#define ST25DV_GetRFA3SS_ALL                                    ST25DVxxKC_GetRFA3SS_ALL 
#define ST25DV_SetRFA3SS_ALL                                    ST25DVxxKC_SetRFA3SS_ALL 
#define ST25DV_GetRFA4SS_PWDCTRL                                ST25DVxxKC_GetRFA4SS_PWDCTRL 
#define ST25DV_SetRFA4SS_PWDCTRL                                ST25DVxxKC_SetRFA4SS_PWDCTRL 
#define ST25DV_GetRFA4SS_RWPROT                                 ST25DVxxKC_GetRFA4SS_RWPROT 
#define ST25DV_SetRFA4SS_RWPROT                                 ST25DVxxKC_SetRFA4SS_RWPROT 
#define ST25DV_GetRFA4SS_ALL                                    ST25DVxxKC_GetRFA4SS_ALL 
#define ST25DV_SetRFA4SS_ALL                                    ST25DVxxKC_SetRFA4SS_ALL 
#define ST25DV_GetI2CSS_PZ1                                     ST25DVxxKC_GetI2CSS_PZ1 
#define ST25DV_SetI2CSS_PZ1                                     ST25DVxxKC_SetI2CSS_PZ1 
#define ST25DV_GetI2CSS_PZ2                                     ST25DVxxKC_GetI2CSS_PZ2 
#define ST25DV_SetI2CSS_PZ2                                     ST25DVxxKC_SetI2CSS_PZ2 
#define ST25DV_GetI2CSS_PZ3                                     ST25DVxxKC_GetI2CSS_PZ3 
#define ST25DV_SetI2CSS_PZ3                                     ST25DVxxKC_SetI2CSS_PZ3 
#define ST25DV_GetI2CSS_PZ4                                     ST25DVxxKC_GetI2CSS_PZ4 
#define ST25DV_SetI2CSS_PZ4                                     ST25DVxxKC_SetI2CSS_PZ4 
#define ST25DV_GetI2CSS_ALL                                     ST25DVxxKC_GetI2CSS_ALL 
#define ST25DV_SetI2CSS_ALL                                     ST25DVxxKC_SetI2CSS_ALL 
#define ST25DV_GetLOCKCCFILE_BLCK0                              ST25DVxxKC_GetLOCKCCFILE_BLCK0 
#define ST25DV_SetLOCKCCFILE_BLCK0                              ST25DVxxKC_SetLOCKCCFILE_BLCK0 
#define ST25DV_GetLOCKCCFILE_BLCK1                              ST25DVxxKC_GetLOCKCCFILE_BLCK1 
#define ST25DV_SetLOCKCCFILE_BLCK1                              ST25DVxxKC_SetLOCKCCFILE_BLCK1 
#define ST25DV_GetLOCKCCFILE_ALL                                ST25DVxxKC_GetLOCKCCFILE_ALL 
#define ST25DV_SetLOCKCCFILE_ALL                                ST25DVxxKC_SetLOCKCCFILE_ALL 
#define ST25DV_GetLOCKCFG_B0                                    ST25DVxxKC_GetLOCKCFG_B0 
#define ST25DV_SetLOCKCFG_B0                                    ST25DVxxKC_SetLOCKCFG_B0 
#define ST25DV_GetI2C_SSO_DYN_I2CSSO                            ST25DVxxKC_GetI2C_SSO_DYN_I2CSSO 

#endif /*_ST25DV_REG_WRAPPER_H_*/

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
