name: Telink TL321x build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build TL321x samples/basic/blinky
      run: |
        cd ..
        west build -b tl3218x     -d build_blinky_tl321x                      zephyr/samples/basic/blinky

    - name: Build TL321x samples/hello_world
      run: |
        cd ..
        west build -b tl3218x     -d build_hello_tl321x                       zephyr/samples/hello_world

    - name: Build TL321x samples/basic/button
      run: |
        cd ..
        west build -b tl3218x     -d build_button_tl321x                      zephyr/samples/basic/button

    - name: Build TL321x samples/sensor/sht3xd
      run: |
        cd ..
        west build -b tl3218x     -d build_sht3xd_tl321x                      zephyr/samples/sensor/sht3xd

    - name: Build TL321x samples/drivers/adc
      run: |
        cd ..
        west build -b tl3218x     -d build_adc_tl321x                         zephyr/samples/drivers/adc

    - name: Build TL321x samples/drivers/watchdog
      run: |
        cd ..
        west build -b tl3218x     -d build_watchdog_tl321x                    zephyr/samples/drivers/watchdog

    - name: Build TL321x tests/drivers/flash/common
      run: |
        cd ..
        west build -b tl3218x     -d build_tests_flash_tl321x                 zephyr/tests/drivers/flash/common

    - name: Build TL321x samples/basic/fade_led/
      run: |
        cd ..
        west build -b tl3218x     -d build_fade_tl321x                        zephyr/samples/basic/fade_led/

    - name: Build TL321x net/openthread/cli
      run: |
        cd ..
        west build -b tl3218x     -d build_ot_cli_tl321x                      zephyr/samples/net/openthread/cli

    - name: Build TL321x net/openthread/coprocessor in RCP configuration with UART interface
      run: |
        cd ..
        west build -b tl3218x     -d build_ot_coprocessor_rcp_uart_tl321x     zephyr/samples/net/openthread/coprocessor     -- -DOVERLAY_CONFIG=overlay-rcp.conf

    - name: Build TL321x subsys/usb/console for USB driver
      run: |
        cd ..
        west build -b tl3218x     -d build_usb_console_tl321x                 zephyr/samples/subsys/usb/console

    - name: Build TL321X net/openthread/coprocessor in RCP configuration with USB interface
      run: |
        cd ..
        west build -b tl3218x     -d build_ot_coprocessor_rcp_usb_tl321x      zephyr/samples/net/openthread/coprocessor     -- -DDTC_OVERLAY_FILE="usb.overlay boards/tl3218x-dongle.overlay" -DOVERLAY_CONFIG=overlay-rcp-usb-telink.conf

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_tl321x/zephyr/zephyr.bin                     telink_build_artifacts/tl321x_blinky.bin
        cp ../build_hello_tl321x/zephyr/zephyr.bin                      telink_build_artifacts/tl321x_hello_world.bin
        cp ../build_button_tl321x/zephyr/zephyr.bin                     telink_build_artifacts/tl321x_button.bin
        cp ../build_sht3xd_tl321x/zephyr/zephyr.bin                     telink_build_artifacts/tl321x_sht3xd.bin
        cp ../build_adc_tl321x/zephyr/zephyr.bin                        telink_build_artifacts/tl321x_adc.bin
        cp ../build_watchdog_tl321x/zephyr/zephyr.bin                   telink_build_artifacts/tl321x_watchdog.bin
        cp ../build_tests_flash_tl321x/zephyr/zephyr.bin                telink_build_artifacts/tl321x_tests_flash.bin
        cp ../build_fade_tl321x/zephyr/zephyr.bin                       telink_build_artifacts/tl321x_tests_pwm.bin
        cp ../build_ot_cli_tl321x/zephyr/zephyr.bin                     telink_build_artifacts/tl321x_ot_cli.bin
        cp ../build_ot_coprocessor_rcp_uart_tl321x/zephyr/zephyr.bin    telink_build_artifacts/tl321x_ot_coprocessor_rcp_uart.bin
        cp ../build_usb_console_tl321x/zephyr/zephyr.bin                telink_build_artifacts/tl321x_usb_console.bin
        cp ../build_ot_coprocessor_rcp_usb_tl321x/zephyr/zephyr.bin     telink_build_artifacts/tl321x_ot_coprocessor_rcp_usb.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
