name: Telink TL321x build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build TL321x basic/blinky
      run: |
        cd ..
        west build -b tl3218x                  -d build_blinky_tl321x                    zephyr/samples/basic/blinky

    - name: Build TL321x basic/blinky with PM
      run: |
        cd ..
        west build -b tl3218x                  -d build_blinky_pm_tl321x                 zephyr/samples/basic/blinky                              -- -DCONFIG_PM=y

    - name: Build TL321x bluetooth/peripheral_ht
      run: |
        cd ..
        west build -b tl3218x                  -d build_bt_peripheral_ht_tl321x          zephyr/samples/bluetooth/peripheral_ht

    - name: Build TL321x bluetooth/peripheral_ht with PM
      run: |
        cd ..
        west build -b tl3218x                  -d build_bt_peripheral_ht_pm_tl321x       zephyr/samples/bluetooth/peripheral_ht                   -- -DCONFIG_PM=y

    - name: Build TL321x net/openthread/coprocessor in RCP configuration with UART interface
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_coprocessor_rcp_uart_tl321x   zephyr/samples/net/openthread/coprocessor                -- -DOVERLAY_CONFIG=overlay-rcp.conf

    - name: Build TL321x net/sockets/echo_server for OpenThread
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_echo_server_tl321x            zephyr/samples/net/sockets/echo_server                   -- -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build TL321x net/sockets/echo_client for OpenThread
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_echo_client_tl321x            zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build TL321x net/sockets/echo_client for OpenThread with PM
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_echo_client_pm_tl321x         zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y

    - name: Build TL321x bootloader/mcuboot/boot
      run: |
        cd ..
        west build -b tl3218x                  -d build_mcuboot_tl321x                   bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=3 -DCONFIG_BOOT_MAX_IMG_SECTORS=4096

    - name: Build TL321x subsys/mgmt/mcumgr/smp_svr for Bluetooth
      run: |
        cd ..
        west build -b tl3218x                  -d build_bt_smp_svr_tl321x                zephyr/samples/subsys/mgmt/mcumgr/smp_svr                -- -DOVERLAY_CONFIG=overlay-bt.conf

    - name: Build TL321x subsys/usb/console for USB driver
      run: |
        cd ..
        west build -b tl3218x                  -d build_usb_console_tl321x               zephyr/samples/subsys/usb/console

    - name: Build TL321x net/openthread/coprocessor in RCP configuration with USB interface
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_coprocessor_rcp_usb_tl321x    zephyr/samples/net/openthread/coprocessor                -- -DDTC_OVERLAY_FILE="usb.overlay boards/tl3218x-dongle.overlay" -DOVERLAY_CONFIG=overlay-rcp-usb-telink.conf

    - name: Build TL321x boards/tlsr9x/basic
      run: |
        cd ..
        west build -b tl3218x_retention        -d build_retention_basic_tl321x           zephyr/samples/boards/tlsr9x/basic                       -- -DCONFIG_SOC_SERIES_RISCV_TELINK_TLX_NON_RETENTION_RAM_CODE=y

    - name: Build TL321x net/sockets/echo_client for OpenThread with PM deep-sleep
      run: |
        cd ..
        west build -b tl3218x_retention        -d build_ot_echo_client_pm_deep_tl321x    zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y -DCONFIG_SOC_SERIES_RISCV_TELINK_TLX_NON_RETENTION_RAM_CODE=y -DCONFIG_TELINK_TLX_2_WIRE_SPI_ENABLE=y

    - name: Build TL321x bootloader/mcuboot/boot for USB DFU
      run: |
        cd ..
        west build -b tl3218x                  -d build_mcuboot_usb_dfu_tl321x           bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=3 -DCONFIG_USB_DFU_WILL_DETACH=n -DCONFIG_BOOT_USB_DFU_GPIO=y -DCONFIG_MCUBOOT_INDICATION_LED=y

    - name: Build TL321x basic/blinky for USB DFU
      run: |
        cd ..
        west build -b tl3218x                  -d build_blinky_usb_dfu_tl321x            zephyr/samples/basic/blinky                              -- -DCONFIG_BOOTLOADER_MCUBOOT=y

    - name: Build TL321x net/openthread/cli
      run: |
        cd ..
        west build -b tl3218x                  -d build_ot_cli_tl321x                    zephyr/samples/net/openthread/cli                        -- -DOVERLAY_CONFIG=overlay-telink-fixed-mac.conf

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_tl321x/zephyr/zephyr.bin                    telink_build_artifacts/tl321x_blinky.bin
        cp ../build_blinky_pm_tl321x/zephyr/zephyr.bin                 telink_build_artifacts/tl321x_blinky_pm.bin
        cp ../build_bt_peripheral_ht_tl321x/zephyr/zephyr.bin          telink_build_artifacts/tl321x_bt_peripheral_ht.bin
        cp ../build_bt_peripheral_ht_pm_tl321x/zephyr/zephyr.bin       telink_build_artifacts/tl321x_bt_peripheral_ht_pm.bin
        cp ../build_ot_coprocessor_rcp_uart_tl321x/zephyr/zephyr.bin   telink_build_artifacts/tl321x_ot_coprocessor_rcp_uart.bin
        cp ../build_ot_echo_server_tl321x/zephyr/zephyr.bin            telink_build_artifacts/tl321x_ot_echo_server.bin
        cp ../build_ot_echo_client_tl321x/zephyr/zephyr.bin            telink_build_artifacts/tl321x_ot_echo_client.bin
        cp ../build_ot_echo_client_pm_tl321x/zephyr/zephyr.bin         telink_build_artifacts/tl321x_ot_echo_client_pm.bin
        cp ../build_mcuboot_tl321x/zephyr/zephyr.bin                   telink_build_artifacts/tl321x_mcuboot.bin
        cp ../build_bt_smp_svr_tl321x/zephyr/zephyr.signed.bin         telink_build_artifacts/tl321x_bt_smp_svr.signed.bin
        cp ../build_usb_console_tl321x/zephyr/zephyr.bin               telink_build_artifacts/tl321x_usb_console.bin
        cp ../build_ot_coprocessor_rcp_usb_tl321x/zephyr/zephyr.bin    telink_build_artifacts/tl321x_ot_coprocessor_rcp_usb.bin
        cp ../build_retention_basic_tl321x/zephyr/zephyr.bin           telink_build_artifacts/tl321x_retention_basic.bin
        cp ../build_ot_echo_client_pm_deep_tl321x/zephyr/zephyr.bin    telink_build_artifacts/tl321x_ot_echo_client_pm_retention.bin
        cp ../build_mcuboot_usb_dfu_tl321x/zephyr/zephyr.bin           telink_build_artifacts/tl321x_mcuboot_usb_dfu.bin
        cp ../build_blinky_usb_dfu_tl321x/zephyr/zephyr.signed.bin     telink_build_artifacts/tl321x_blinky_usb_dfu.signed.bin
        cp ../build_ot_cli_tl321x/zephyr/zephyr.bin                    telink_build_artifacts/tl321x_ot_cli.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
